services:
  - type: web
    name: nature-sound-translator
    env: python
    buildCommand: |
      apt-get update && apt-get install -y python3-distutils
      pip install -r requirements.txt
    startCommand: gunicorn app:app
